#!/bin/sh

# Set these paths appropriately

BIN="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/bin"
CMD="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/cmd"
LIB="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
