#!/bin/sh

# Set these paths appropriately

BIN="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/bin"
CMD="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/cmd"
LIB="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

