#!/bin/sh

# Set these paths appropriately

BIN="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/bin"
CMD="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/cmd"
LIB="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/polish-abbreviations
PARFILE=${LIB}/polish.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
