#!/bin/sh

# Set these paths appropriately

BIN="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/bin"
CMD="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/cmd"
LIB="/home/dbelveze/Bureau/TERMSUITE_WORKSPACE/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
